name: PyPI
on:
  push:
    tags:
    - v*.*.*
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Create source distribution
      run: python setup.py sdist
    - name: Create (binary) wheel distributions
      uses: pypa/cibuildwheel@v2.2.2
      with:
        output-dir: dist
      env:
        CIBW_BEFORE_BUILD: pip install -r requirements.txt
    - name: Publish distributions to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
